### ISSUE TITLE
Annoying version-related warning

### ISSUE THREAD

**Issue by pombredanne** [kojiromike/parameter-expansion#24]
Somehow (not sure in which exact context) it is common that I get this annoying warning:
> f"Unable to determine version for {name}. Falling back to {_default_version}"
> /parameter_expansion/__init__.py:40: UserWarning: Unable to determine version for parameter_expansion. Falling back to 0.0.0+unknown

I am not sure I understand the ways versioning is handled in the project. I find it a bit surprising or at least uncommon

**Comment by pombredanne** [comment]
@kojiromike gentle ping... this warning is really annoying and I am receiving several complaints from users.... is there something we can do to simplify this? Alternatively I can make a temp fork and release this without this warning

**Comment by kojiromike** [comment]
This warning is basically saying that the way parameter-expansion is being packaged or installed is not generating or maintaining the correct version metadata. It's quite possible this is my fault for switching from using [setuptools-scm](https://pypi.org/project/setuptools-scm/) to using [poetry-dynamic-versioning](https://pypi.org/project/poetry-dynamic-versioning/), as the latter seems to be less reliable, but I didn't immediately encounter this problem trying to use the package myself, so I'm not entirely sure.

I had been in the process of building a simpler approach to packaging and versioning. I want to just explicitly version the thing in pyproject.toml, but with the additional goal of having that mesh with the pull-request process, so that by the time a pull request is ready to merge, the semantic version that goes with the merge will be known. But I didn't make enough progress on this to be comfortable putting it in this project before I had some personal stuff come up and had to step away.

At this point, since we're still manually releasing to pypi anyway, I think manually versioning is probably the right way to go until I can finish the automation. (I just don't want to accidentally end up with two trunk commits that have the same version declared in pyproject.toml.)

If you want to help, just make a PR that rips out the poetry-dynamic-versioning in pyproject.toml and hard-codes the next patch release.

### Warnings Control

Some users may benefit from a quick reminder that [warnings in Python are easy to ignore](https://docs.python.org/3/library/warnings.html#warning-filter). For example:

#### No warnings filter

Without a warnings filter, this command produces a warning…

```
$ python -c 'import warnings;name="parameter-expansion";_default_version="0.0.0+unknown";warnings.warn(
        UserWarning(
            f"Unable to determine version for {name}. Falling back to {_default_version}"
        )
    )'
<string>:1: UserWarning: Unable to determine version for parameter-expansion. Falling back to 0.0.0+unknown
```

#### With warnings filter

With a filter, there is no output…

```
$ PYTHONWARNINGS='ignore:Unable to determine version for parameter-expansion' \
    python -c 'import warnings;name="parameter-expansion";_default_version="0.0.0+unknown";warnings.warn(
        UserWarning(
            f"Unable to determine version for {name}. Falling back to {_default_version}"
        )
    )'
```
